version: "3.3"
services:
  db:
    image: mysql:8.0.17
    container_name: goldenblock_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    volumes:                                                                                                              
      - ${pwd}/mysql:/var/lib/mysql

    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
